# Generated by Django 4.1.2 on 2022-11-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artobjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artobjects',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artobjects',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artobjects',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
