# Generated by Django 4.1.3 on 2022-11-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artobjects', '0003_alter_artobjects_current_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artobjects',
            name='current_price',
        ),
    ]
