# Generated by Django 4.1.3 on 2022-11-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0005_alter_userextend_firstname_alter_userextend_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='account',
        ),
        migrations.AddField(
            model_name='userextend',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextend',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
