# Generated by Django 4.1.3 on 2022-11-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('starting_price', models.CharField(max_length=10)),
                ('final_price', models.CharField(max_length=10)),
            ],
        ),
    ]
