# Generated by Django 4.1.3 on 2022-11-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jewelery',
            new_name='Jewellery',
        ),
    ]
